# Numpy Arrays
- Numpy array is a grid of values all of the same type
- Indexed by the tuple of non negative integers
- Rank of the array - the number of dimensions 
- Shape of the array - tuple of integers giving the size of the array along each dimension 
- can initialise the numpy array using Python lists and access the elements using square brackets

In [2]:
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1])
a[0]=5
print(a[0])

#creating an array of rank 2
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0])
print(b)

<class 'numpy.ndarray'>
(3,)
1 2
5
(2, 3)
1
[[1 2 3]
 [4 5 6]]


## 1.0 Numpy functions to create arrays

In [2]:
a=np.zeros((2,2)) #to create an array of all zeroes
print(a)

b=np.ones((2,2)) #to create an array with all the values as 1s
print(b) 

c=np.full((2,2),7) #to create an array with dimensions 2*2 and with the constant value 7
print(c)

d=np.eye(2) #to create an identity matrix with dimensions of 2*2
print(d)

e=np.random.random((2,2)) #to create an array of 2*2 dimensions with all the random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.39564199 0.85355441]
 [0.41304231 0.84191698]]


### 1.1 Indexing an Array 
- Must specify a splice for each dimension of the array because arrays are multi dimensional
- Slice indexing starts from 1 whereas the integer indexing starts from 0

In [10]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a[:2,2:4]  #this is only a view of the array b, modifying b will modify a, indexing starts from 1
print(b)
print(b.shape)
print(b[0,0])
b[0,0]=100
print(a[0,2])
print(b[0,0])
b[0,0]=3

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
(2, 2)
3
100
100


In [11]:
print(a)
row_r1=a[0,:]  #here 1 means row 1, indexing from 0 and just a : indicates all columns
print(row_r1,row_r1.shape)
row_r2=a[1:2,:]
print(row_r2,row_r2.shape)
col_c1=a[:,0]  #all rows first column
print(col_c1,col_c1.shape)
col_c2=a[:,1:2]  #all rows second column
print(col_c2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4] (4,)
[[5 6 7 8]] (1, 4)
[1 5 9] (3,)
[[ 2]
 [ 6]
 [10]]


In [18]:
a=[1,0,3,4,0,6]
print(a)
print(np.sum(a[3:6]))
print(np.argmin(a[:3]))
print(np.argmin(a[3:6])+3)
for i in range(3,6):
    print(i)
print(np.argmax(a[3:6])+3)

[1, 0, 3, 4, 0, 6]
10
1
4
3
4
5
5


In [9]:
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
print(inputs[0].reshape(1,2))
overall_error=10.0
newone=[]
newone.append(overall_error)
print(f"Before overall_error {newone}")
overall_error=20.0
newone.append(overall_error)
print(f"After overall_error {newone}")

[[0 0]]
Before overall_error [10.0]
After overall_error [10.0, 20.0]


#### 1.1.1 Integer Indexing
- indexing numpy arrays using slicing will result in the subarrays which are the views of the original arrays
- to construct new arrays - usage of integer indexing

In [5]:
a=np.array([[1,2],[3,4],[5,6]])
print(a,a.shape)
print(a[[0,1,2],[0,1,0]]) #this selects 0,0 and 1,1 and 2,0
b=a[[0,1,2],[0,1,0]]
print(b)
b[[0,0]]=100
print(b)
print(a)  #this proves that it is an array and not the view of the array

#you can reuse the same element from the original array
print(a[[0,0],[1,1]])  #prints 0,1 and 0,1

#can use another array to extract the indices
c=np.array([1,0])
d=a[np.arange(1),c] #np.range will arrange the numbers from 0 to the current number
print(d)
a[np.arange(1),c]+=10  #a was 1,2 3,4 5,6
print(a)
a[np.arange(1),c]-=10
print(a)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 4 5]
[1 4 5]
[100   4   5]
[[1 2]
 [3 4]
 [5 6]]
[2 2]
[2 1]
[[11 12]
 [ 3  4]
 [ 5  6]]
[[1 2]
 [3 4]
 [5 6]]


#### 1.1.2 Boolean array Indexing
- lets to pick out arbitrary elements of an array

In [6]:
bool_idx=(a>2)    
print(bool_idx)
print(a[bool_idx]) #prints only those elements which are greater than 2
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## 2.0 Datatypes
- Numpy guesses the datatype when we create it 
- But also we can specify the datatypes when we create
- There are other datatypes too which are not covered below

In [7]:
x=np.array([1,2])
print(x.dtype)
x=np.array([3,4],dtype=np.int64)
print(x,x.dtype)

int64
[3 4] int64


## 3.0 Array Math
- Basic mathematical functions operate elementwise on arrays
- As operators overloads and also as functions

### Dot Products
- \* is the element wise multiplication
- Dot Function
    - to compute the inner products of the vectors
    - to multiply a vector by a matrix
    - to multiply matrices
    - available as a numpy function
    - available as an instance method of numpy objects

In [8]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

#elementwise sum both give the arrays : operator overloading and function
print(x+y)
print(np.add(x,y))

#elementwise subtract
print(x-y)
print(np.subtract(x,y))

#elementwise product
print(x*y)
print(np.multiply(x,y))

#elementwise division
print(x/y)
print(np.divide(x,y))

#elementwise squareroot
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [9]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
v=np.array([9,10])
w=np.array([11,12])

#inner product of vectors
print(v.dot(w))
print(np.dot(v,w))

#matrix or the vector product
print(x.dot(v))
print(np.dot(x,v))

#matrix to matrix product
print(x.dot(y))
print(np.dot(x,y))

219
219
[29. 67.]
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


### Other functions on the arrays

In [10]:
x=np.array([[1,2],[3,4]])
print(np.sum(x)) # sum of all the elements of the array
print(np.sum(x,axis=0)) #sum of every column of the array
print(np.sum(x,axis=1)) #sum of every row of the array

#Transpose of matrix
print(x)
print(x.T)

#transposing of a rank 1 array does nothing

10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## Broadcasting
1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [11]:
#add the vector to each row of the matrix
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
