In [2]:
from __future__ import print_function
import torch

#uninitialised matrix of 5*3 in pytorch
x=torch.empty(5,3)
print(x)

#randomly uninitialised 5*3 matrix
x=torch.rand(5,3)
print(x)

#matrix of zeroes and of the datatype long
x=torch.zeros(5,3,dtype=torch.long)
print(x)

x=torch.tensor([5.5,3])
print(x)

#create a new tensor based on an existing tensor
x=x.new_ones(5,3,dtype=torch.double)
print(x)
#same dimensions as x but overriding the dtype
x=torch.randn_like(x,dtype=torch.float)
print(x)

#to print the size of the tensor
print(x.size())
#torch.size is a tuple and it supports all tuple operations

tensor([[4.7414e+16, 3.1434e-12, 8.0775e+17],
        [1.4583e-19, 4.1486e-08, 1.3556e-19],
        [1.8567e-01, 1.2043e-32, 1.3563e-19],
        [1.8888e+31, 4.7414e+16, 4.0047e-11],
        [6.4097e-10, 5.8253e-10, 6.4097e-10]])
tensor([[0.3982, 0.7172, 0.2691],
        [0.7341, 0.4943, 0.0773],
        [0.3557, 0.5978, 0.7238],
        [0.8451, 0.2157, 0.1492],
        [0.8975, 0.4766, 0.5946]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5598,  0.2589, -1.4018],
        [ 0.0256,  1.0924, -1.0235],
        [-1.3870,  0.2484,  2.9512],
        [-0.1714,  0.6173, -1.5169],
        [-0.9064, -0.0053, -1.6680]])
torch.Size([5, 3])


## Operations in Pytorch
- Addition - two possible
- an operation which mutates the tensor in place is postfixed with _ x.copy_() will change x. Simlarly other in place operations
- To resize a tensor use (tensor).view
- Other tensor operations https://pytorch.org/docs/stable/torch.html
- All tensors except the chartensor can be converted to the Numpy and vice versa

In [20]:
#Operations of Pytorch

y=torch.rand(5,3)
print(x+y)  # one of the syntaxes of addition
print(torch.add(x,y)) #second syntax for addition

#output as a tensor
result=x+y
print(result)
torch.add(x,y,out=result)
print(result)

#in place addition - adds x to y
y.add_(x)
print(y)

tensor([[ 2.3189,  0.1046,  0.3333],
        [ 0.5114,  0.7004, -0.4639],
        [-0.1431,  0.3312,  0.7110],
        [-0.0720, -0.6239,  1.1720],
        [-0.8311,  1.6144,  0.0330]])
tensor([[ 2.3189,  0.1046,  0.3333],
        [ 0.5114,  0.7004, -0.4639],
        [-0.1431,  0.3312,  0.7110],
        [-0.0720, -0.6239,  1.1720],
        [-0.8311,  1.6144,  0.0330]])
tensor([[ 2.3189,  0.1046,  0.3333],
        [ 0.5114,  0.7004, -0.4639],
        [-0.1431,  0.3312,  0.7110],
        [-0.0720, -0.6239,  1.1720],
        [-0.8311,  1.6144,  0.0330]])
tensor([[ 2.3189,  0.1046,  0.3333],
        [ 0.5114,  0.7004, -0.4639],
        [-0.1431,  0.3312,  0.7110],
        [-0.0720, -0.6239,  1.1720],
        [-0.8311,  1.6144,  0.0330]])
tensor([[ 2.3189,  0.1046,  0.3333],
        [ 0.5114,  0.7004, -0.4639],
        [-0.1431,  0.3312,  0.7110],
        [-0.0720, -0.6239,  1.1720],
        [-0.8311,  1.6144,  0.0330]])


In [27]:
print(x)
print(x[:,1]) #prints the column at index 1 (i.e. 2nd column)

tensor([[ 1.4389, -0.3004, -0.0874],
        [-0.2956, -0.1454, -0.7984],
        [-0.7909, -0.1825, -0.1275],
        [-0.2338, -1.3596,  0.6850],
        [-1.3156,  0.8451, -0.9145]])
tensor([-0.3004, -0.1454, -0.1825, -1.3596,  0.8451])


In [35]:
x=torch.randn(4,4)
print(x)
y=x.view(16)
print(y.size())
z=x.view(-1,8) #the size -1 is inferred from other dimensions (dunno what this means)
print(z)
print(z.size())

#if you have a one element tensor, use .item to the get the value as the python number
x=torch.randn(1)
print(x) #this prints as a matrix
print(x.item()) #this prints as a python number

tensor([[-0.2086, -0.2047, -0.1165, -0.5127],
        [ 0.2755,  1.7972, -0.4807, -0.0735],
        [-0.6559,  2.6421,  0.5717,  1.9044],
        [-0.3256,  0.0643, -0.2601, -1.0877]])
torch.Size([16])
tensor([[-0.2086, -0.2047, -0.1165, -0.5127,  0.2755,  1.7972, -0.4807, -0.0735],
        [-0.6559,  2.6421,  0.5717,  1.9044, -0.3256,  0.0643, -0.2601, -1.0877]])
torch.Size([2, 8])
tensor([1.0554])
1.0554451942443848


In [44]:
#converting torch tensor to a numpy array
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

#operations done on a will change the numpy array b also
a.add_(1)
print(a)
print(b)

#converting numpy array to a torch tensor
import numpy as np
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Autograd Package
- Central to all neural networks in Pytorch is the autograd package
- autograd package provides automatic differentiation for all operations on tensors
- Define-by-run framework
    - this means that my backprop is defined by how my code is run, and that every single iteration can be different

### Tensor
- torch.tensor is the central class of the package
- if the attribute of the class torch.tensor, .requires_grad as True, then it starts to track all the operations on it (on the attribute?)
- .backward() can be called after the operations to calculate the gradients automatically. The gradient for this tensor will be accumulated into the .grad attribute
- To stop a tensor from calling history you can call the .detach() to detach it from the computation history
- to prevent tracking history wrap the code block in "with torch.no_grad():"
- Function class is also important for autograd implementation
- Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation
    - Each tensor has a .grad_fn attribute that references a function that has created the tensor
- to compute the derivatives, call backward function on a tensor
    - if a tensor is scalar,then no arguments for the the backward function
    - tensor is non-scalar then speficy a gradient argument that is a tensor of matching shape

In [52]:
x=torch.ones(2,2,requires_grad=True)
print(x)

y=x+2 #adds 2 to every element of the tensor
print(y.grad_fn)

z=y*y*3
out=z.mean() #returns the mean value of each dimension of the tensor
print(z,out)

#requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
False
True


In [62]:
#GRADIENTS
x=torch.ones(2,2,requires_grad=True)
print(x)

y=x+2 #adds 2 to every element of the tensor
print(y.grad_fn)

z=y*y*3
out=z.mean() #returns the mean value of each dimension of the tensor
print(z,out)

out.backward(retain_graph=True) #out contains a single scalar so out.backward is equivalent to out.backward(torch.tensor(1,))
print(x.grad)



tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [12]:
#torch.autograd is an engine for computing vector-Jacobian product
#the characteristic of a vector Jacobian product makes it very convenient to feed external gradients to a model that has non scalar output
x=torch.randn(3,requires_grad=True)
y=x*2
print(y)
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

#to stop tracking history with tensors use .requires_grad=True or enclose the code block with torch.no_grad()
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)
    
print((x**2).requires_grad)

#using detach get a new tensor with the same content but that does not require gradients
print(x.requires_grad)
y=x.detach()
print(y.requires_grad)  #by default the grad is false
print(x.eq(y).all())
print(x)
print(y)

tensor([-0.2430,  1.2260,  2.2465], grad_fn=<MulBackward0>)
tensor([2.0000e-01, 2.0000e+00, 2.0000e-04])
True
True
False
True
True
False
tensor(True)
tensor([-0.1215,  0.6130,  1.1233], requires_grad=True)
tensor([-0.1215,  0.6130,  1.1233])


"[The trio] realizes they’re never going to be able to feel relief. They’re always going to feel the stress, the fear of Voldemort coming closer, being ever present, being such a danger."
- Casper on relief in Book 7, Chapter 9

"Oh, damn, that'll be the books," Hermione said, peering into it, "and I had them all stacked by subject..."
-Chapter 9 - when we're introduced to Hermione's bag with its undetectable extension charm!